Repository mlange-42/tiny-world, pull requests merged in 2024-03, with the labels that each got.

#66 Random variants shown in cards and persist when building
  game/render/terrain.go
  game/res/factory.go
  game/res/selection.go
  game/res/ui.go
  game/sys/build.go
  game/sys/init_terrain.go
  main.go
Labels: feature, graphics

#71 Castles are required to extend the build radius
  artwork/sprites/paper/full_48x48/castle/castle.png
  artwork/sprites/paper/full_48x48/castle/castle.xcf
  artwork/sprites/paper/full_48x48/castle/tower.png
  artwork/sprites/paper/full_48x48/castle/tower.xcf
  data/gfx/paper/full_48x48.json
  data/gfx/paper/full_48x48.png
  data/json/rules.json
  data/json/terrain.json
  game/comp/components.go
  game/nav/astar.go
  game/render/terrain.go
  game/res/factory.go
  game/res/rules.go
  game/res/ui.go
  game/sys/build.go
  game/sys/cheats.go
  game/sys/haul.go
  game/sys/init_terrain.go
  game/sys/init_terrain_loaded.go
  game/sys/update_stats.go
  game/terr/terrain.go
  game/util/buildable.go
  main.go
Labels: feature

#76 Fix render extent to cover the full screen for high sprites
  game/res/view.go
Labels: graphics

#77 Savegame support for WASM/web version
  README.md
  embed.go
  game/menu/draw_ui.go
  game/menu/ui.go
  game/menu/update_ui.go
  game/res/save_event.go
  game/res/ui.go
  game/run.go
  game/run_nowasm.go
  game/run_wasm.go
  game/save/load.go
  game/save/load_nowasm.go
  game/save/load_wasm.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/save_wasm.go
  game/sys/save_game.go
  main.go
Labels: infrastructure

#83 Implement explicit bulldozing
  artwork/sprites/paper/full_48x48/bulldoze/bulldoze.png
  artwork/sprites/paper/full_48x48/bulldoze/bulldoze.xcf
  data/gfx/paper/full_48x48.json
  data/gfx/paper/full_48x48.png
  data/json/terrain.json
  game/render/terrain.go
  game/res/ui.go
  game/sys/build.go
  game/terr/terrain.go
Labels: feature

#88 Add tower as low range military/build radius building
  artwork/sprites/paper/full_48x48/castle/castle.png
  artwork/sprites/paper/full_48x48/castle/castle.xcf
  artwork/sprites/paper/full_48x48/castle/tower.png
  artwork/sprites/paper/full_48x48/castle/tower.xcf
  artwork/sprites/paper/full_48x48/castle/tower_large.xcf
  data/gfx/paper/full_48x48.png
  data/json/terrain.json
  game/res/ui.go
Labels: feature

#93 Visualize the buildable area
  artwork/sprites/paper/flat_48x24/border/border_inner.json
  artwork/sprites/paper/flat_48x24/border/border_inner.png
  artwork/sprites/paper/flat_48x24/border/border_inner_01.png
  artwork/sprites/paper/flat_48x24/border/border_inner_02.png
  artwork/sprites/paper/flat_48x24/border/border_inner_03.png
  artwork/sprites/paper/flat_48x24/border/border_inner_04.png
  artwork/sprites/paper/flat_48x24/border/border_inner_05.png
  artwork/sprites/paper/flat_48x24/border/border_inner_06.png
  artwork/sprites/paper/flat_48x24/border/border_inner_07.png
  artwork/sprites/paper/flat_48x24/border/border_inner_08.png
  artwork/sprites/paper/flat_48x24/border/border_inner_09.png
  artwork/sprites/paper/flat_48x24/border/border_inner_10.png
  artwork/sprites/paper/flat_48x24/border/border_inner_11.png
  artwork/sprites/paper/flat_48x24/border/border_inner_12.png
  artwork/sprites/paper/flat_48x24/border/border_inner_13.png
  artwork/sprites/paper/flat_48x24/border/border_inner_14.png
  artwork/sprites/paper/flat_48x24/border/border_inner_15.png
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_inner.json
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_inner.png
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_inner.xcf
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_outer.json
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_outer.png
  artwork/sprites/paper/flat_48x24/border/border_multitile/border_outer.xcf
  artwork/sprites/paper/flat_48x24/border/border_outer.json
  artwork/sprites/paper/flat_48x24/border/border_outer.png
  artwork/sprites/paper/flat_48x24/border/border_outer_01.png
  artwork/sprites/paper/flat_48x24/border/border_outer_02.png
  artwork/sprites/paper/flat_48x24/border/border_outer_03.png
  artwork/sprites/paper/flat_48x24/border/border_outer_04.png
  artwork/sprites/paper/flat_48x24/border/border_outer_05.png
  artwork/sprites/paper/flat_48x24/border/border_outer_06.png
  artwork/sprites/paper/flat_48x24/border/border_outer_07.png
  artwork/sprites/paper/flat_48x24/border/border_outer_08.png
  artwork/sprites/paper/flat_48x24/border/border_outer_09.png
  artwork/sprites/paper/flat_48x24/border/border_outer_10.png
  artwork/sprites/paper/flat_48x24/border/border_outer_11.png
  artwork/sprites/paper/flat_48x24/border/border_outer_12.png
  artwork/sprites/paper/flat_48x24/border/border_outer_13.png
  artwork/sprites/paper/flat_48x24/border/border_outer_14.png
  artwork/sprites/paper/flat_48x24/border/border_outer_15.png
  artwork/sprites/paper/full_48x48/grass/grass.json
  artwork/sprites/paper/full_48x48/grass/grass_multitile/grass.json
  data/gfx/paper/flat_48x24.json
  data/gfx/paper/flat_48x24.png
  data/gfx/paper/full_48x48.json
  game/render/terrain.go
  game/res/factory.go
  game/res/sprites.go
  game/res/terrain.go
  game/run.go
  game/save/save.go
  game/sprites/sprites.go
  game/sys/build.go
  game/sys/init_terrain.go
  game/sys/init_terrain_loaded.go
  game/util/buildable.go
Labels: feature, graphics

#94 Show border when building, no matter what
  game/render/terrain.go
Labels: graphics

#95 Indicators for production, storage and population support
  artwork/sprites/paper/tiny_8x8/indicators/indicator_population.png
  artwork/sprites/paper/tiny_8x8/indicators/indicator_population.xcf
  artwork/sprites/paper/tiny_8x8/indicators/indicator_population_inactive.png
  artwork/sprites/paper/tiny_8x8/indicators/indicator_production.png
  artwork/sprites/paper/tiny_8x8/indicators/indicator_production.xcf
  artwork/sprites/paper/tiny_8x8/indicators/indicator_production_inactive.png
  artwork/sprites/paper/tiny_8x8/indicators/indicator_storage.png
  artwork/sprites/paper/tiny_8x8/indicators/indicator_storage.xcf
  artwork/sprites/paper/tiny_8x8/indicators/indicator_storage_inactive.png
  data/gfx/paper/tiny_8x8.json
  data/gfx/paper/tiny_8x8.png
  game/render/terrain.go
  game/sprites/sprites.go
Labels: feature, graphics

#97 Maintenance costs for castles, towers, bridges and mills
  data/json/terrain.json
  game/comp/components.go
  game/res/factory.go
  game/res/ui.go
  game/sys/do_consumption.go
  game/sys/update_production.go
  game/sys/update_stats.go
  game/terr/terrain.go
Labels: feature

#98 Add info on special terrain to tooltips
  game/res/ui.go
Labels: usability

#99 Game speed controls
  README.md
  game/res/game_speed.go
  game/run.go
  game/save/save.go
  game/sys/pause.go
Labels: feature

#100 Fix: Ignore error on missing save folder
  game/save/load_nowasm.go
Labels: bug

#103 Fix hauler crash, remove hauler instead
  game/sys/assign_haulers.go
Labels: bug

#102 Style the UI, fix button graphics
  artwork/sprites/paper/high_48x96/cursor/cursor_denied.png
  artwork/sprites/paper/high_48x96/cursor/cursor_denied.xcf
  artwork/sprites/paper/high_48x96/cursor/cursor_destroy.png
  artwork/sprites/paper/high_48x96/cursor/cursor_destroy.xcf
  artwork/sprites/paper/high_48x96/cursor/cursor_neutral.png
  artwork/sprites/paper/high_48x96/cursor/cursor_neutral.xcf
  artwork/sprites/paper/high_48x96/cursor/cursor_ok.png
  artwork/sprites/paper/high_48x96/cursor/cursor_ok.xcf
  artwork/sprites/paper/tileset.json
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel.png
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel.xcf
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel_hover.png
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel_hover.xcf
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel_pressed.png
  artwork/sprites/paper/tiny_16x16/ui_panel/ui_panel_pressed.xcf
  data/gfx/paper/high_48x96.png
  data/gfx/paper/tileset.json
  data/gfx/paper/tiny_16x16.json
  data/gfx/paper/tiny_16x16.png
  game/res/ui.go
  game/sprites/sprites.go
  game/sys/update_stats.go
  game/util/format.go
Labels: graphics

#106 Add a shortkey to toggle fullscreen
  README.md
  game/run.go
  game/sys/game_controls.go
Labels: feature

#108 Add tooltips to info bar, use pixel font
  README.md
  data/fonts/JupiteroidRegular.ttf
  data/fonts/LessRoundBox.ttf
  data/fonts/justabit.ttf
  docs/DESIGN_DOC.md
  game/res/fonts.go
  game/res/ui.go
  game/util/format.go
Labels: graphics, usability

#111 Detect mouse inside, hide cursor
  game/game.go
  game/render/terrain.go
  game/res/mouse.go
  game/run.go
  game/run_nowasm.go
  game/run_wasm.go
  game/save/save.go
Labels: enhancement

#112 Delete save-games via a context menu
  game/game.go
  game/menu/ui.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/save_wasm.go
Labels: usability

#116 Existing terrain aligns to the cursor
  game/render/terrain.go
  game/res/terrain.go
Labels: graphics

#117 Prevent negative stock - derive explicitly if consumption needs are satisfied
  game/comp/components.go
  game/sys/do_consumption.go
  game/sys/update_production.go
Labels: enhancement

#118 Fix align to cursor with nothing selected
  game/render/terrain.go
Labels: bug, graphics

#122 Align terrain only to buildable cursor (not bulldoze)
  game/render/terrain.go
Labels: graphics

#123 Upgrade `ebitenui` to fix tooltip freeze
  go.mod
  go.sum
Labels: bug

#125 Fix path crash: check that there is a path
  game/sys/assign_haulers.go
Labels: bug

#130 Keyboard controls for pan and zoom
  README.md
  game/res/ui.go
  game/res/view.go
  game/run.go
  game/sys/pan_and_zoom.go
Labels: usability

#131 Highlight selected terrain / land use
  game/res/ui.go
  game/sys/build.go
Labels: graphics, usability

#132 Keep random cards/buttons in place
  game/res/ui.go
Labels: usability

#134 Card animations to better show replacement
  game/comp/components.go
  game/render/card_animation.go
  game/render/markers.go
  game/res/ui.go
  game/run.go
  game/sys/build.go
Labels: graphics, usability

#135 Do not apply pause to card animations
  game/render/card_animation.go
  game/res/game_speed.go
  game/res/ui.go
  game/sys/build.go
  game/sys/tick.go
Labels: graphics

#138 Graphics tweaks - trees and terrain boxes
  README.md
  artwork/sprites/paper/full_48x48/grass/grass.png
  artwork/sprites/paper/full_48x48/grass/grass_01.png
  artwork/sprites/paper/full_48x48/grass/grass_02.png
  artwork/sprites/paper/full_48x48/grass/grass_03.png
  artwork/sprites/paper/full_48x48/grass/grass_04.png
  artwork/sprites/paper/full_48x48/grass/grass_05.png
  artwork/sprites/paper/full_48x48/grass/grass_06.png
  artwork/sprites/paper/full_48x48/grass/grass_07.png
  artwork/sprites/paper/full_48x48/grass/grass_08.png
  artwork/sprites/paper/full_48x48/grass/grass_09.png
  artwork/sprites/paper/full_48x48/grass/grass_10.png
  artwork/sprites/paper/full_48x48/grass/grass_11.png
  artwork/sprites/paper/full_48x48/grass/grass_12.png
  artwork/sprites/paper/full_48x48/grass/grass_13.png
  artwork/sprites/paper/full_48x48/grass/grass_14.png
  artwork/sprites/paper/full_48x48/grass/grass_15.png
  artwork/sprites/paper/full_48x48/grass/grass_multitile_off/grass_base.png
  artwork/sprites/paper/full_48x48/grass/grass_multitile_off/grass_base.xcf
  artwork/sprites/paper/full_48x48/tree/tree_c_01.png
  artwork/sprites/paper/full_48x48/tree/tree_c_01.xcf
  artwork/sprites/paper/full_48x48/tree/tree_c_02.png
  artwork/sprites/paper/full_48x48/tree/tree_c_02.xcf
  artwork/sprites/paper/full_48x48/tree/tree_d_01.png
  artwork/sprites/paper/full_48x48/tree/tree_d_01.xcf
  artwork/sprites/paper/full_48x48/tree/tree_d_02.png
  artwork/sprites/paper/full_48x48/tree/tree_d_02.xcf
  data/gfx/paper/full_48x48.png
Labels: graphics

#141 Set up release pipeline
  .github/workflows/release.yml
Labels: infrastructure

#144 Fix: no terrain change below existing land use
  game/sys/build.go
Labels: bug, game rules

#110 Full multitile template
  artwork/sprites/paper/template_multitile_7x7.png
  artwork/sprites/paper/template_multitile_7x7.xcf
Labels: graphics

#147 Ttweak water multitile
  artwork/sprites/paper/flat_48x24/water/water_01.png
  artwork/sprites/paper/flat_48x24/water/water_02.png
  artwork/sprites/paper/flat_48x24/water/water_04.png
  artwork/sprites/paper/flat_48x24/water/water_08.png
  artwork/sprites/paper/flat_48x24/water/water_multitile/water.png
  artwork/sprites/paper/flat_48x24/water/water_multitile/water.xcf
  data/gfx/paper/flat_48x24.png
Labels: graphics

#152 Retrict pan to built-up area, amend bridge tooltip
  data/json/terrain.json
  game/res/factory.go
  game/res/view.go
  game/res/world_bounds.go
  game/run.go
  game/sys/init_terrain.go
  game/sys/pan_and_zoom.go
  game/util/rect.go
Labels: usability

#155 Fix cobra mouse trap, update README
  README.md
  game/run_nowasm.go
Labels: bug

#158 Add random variants for grass tiles
  CHANGELOG.md
  artwork/sprites/paper/full_48x48/grass/grass.json
  artwork/sprites/paper/full_48x48/grass/grass_15.xcf
  artwork/sprites/paper/full_48x48/grass/grass_15_r1.png
  artwork/sprites/paper/full_48x48/grass/grass_15_r2.png
  artwork/sprites/paper/full_48x48/grass/grass_15_r3.png
  artwork/sprites/paper/full_48x48/grass/grass_15_r4.png
  data/gfx/paper/full_48x48.json
  data/gfx/paper/full_48x48.png
Labels: graphics

#159 Document (ECS) resources
  CHANGELOG.md
  game/game.go
  game/menu/draw_ui.go
  game/render/card_animation.go
  game/render/center_view.go
  game/render/hauler_paths.go
  game/render/markers.go
  game/render/terrain.go
  game/render/ui.go
  game/res/factory.go
  game/res/fonts.go
  game/res/game_speed.go
  game/res/image.go
  game/res/mouse.go
  game/res/production.go
  game/res/rules.go
  game/res/save_event.go
  game/res/selection.go
  game/res/sprites.go
  game/res/stock.go
  game/res/ui.go
  game/res/update.go
  game/res/view.go
  game/res/world_bounds.go
  game/save/save.go
  game/sys/pan_and_zoom.go
Labels: documentation

#163 Haulers stay in buildings for a second
  CHANGELOG.md
  game/sys/assign_haulers.go
  game/sys/haul.go
Labels: graphics, game rules

#164 Tweak info labels to accommodate 3-digit values without size changes
  CHANGELOG.md
  game/res/ui.go
  game/sys/init_terrain.go
Labels: graphics

#168 Game can be started on pre-defined maps
  .gitignore
  CHANGELOG.md
  data/json/terrain.json
  data/maps/Desert Valley.asc
  data/maps/River.asc
  data/maps/Swamp Forest.asc
  game/menu/ui.go
  game/res/factory.go
  game/run.go
  game/run_nowasm.go
  game/run_wasm.go
  game/save/load.go
  game/save/load_nowasm.go
  game/save/load_wasm.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/save_wasm.go
  game/sys/init_terrain_map.go
  game/sys/save_game.go
  game/terr/terrain.go
Labels: feature, game rules

#172 Restart the main menu after deleting a savegame
  CHANGELOG.md
  game/game.go
  game/menu/ui.go
  game/run.go
Labels: usability

#179 In-game access to main menu / quit game
  CHANGELOG.md
  game/res/save_event.go
  game/res/sprites.go
  game/res/ui.go
  game/run.go
  game/sys/save_game.go
Labels: feature, usability

#180 Remove unused watermill sprite
  artwork/sprites/paper/full_48x48/watermill/watermill.json
  artwork/sprites/paper/full_48x48/watermill/watermill.png
  data/gfx/paper/full_48x48.json
  data/gfx/paper/full_48x48.png
Labels: graphics

#183 Show build radius around the cursor when building castle or tower
  CHANGELOG.md
  game/render/terrain.go
Labels: graphics, usability

#185 Add info why building is disabled to tooltips
  CHANGELOG.md
  game/res/ui.go
  game/sys/update_stats.go
Labels: usability

#186 Highlight resources with negative net production in the info bar
  CHANGELOG.md
  artwork/sprites/paper/tileset.json
  cmd/util/data.go
  data/gfx/paper/tileset.json
  game/res/sprites.go
  game/res/ui.go
  game/sys/update_stats.go
Labels: usability

#190 Add a "Save map" button to the in-game menu
  CHANGELOG.md
  game/res/save_event.go
  game/res/ui.go
  game/sys/save_game.go
Labels: usability, ui

#187 Implement basics of achievements
  .gitignore
  data/json/achievements.json
  game/res/achievements.go
  game/res/stock.go
  game/resource/resources.go
  game/run.go
  game/save/load.go
  game/save/load_nowasm.go
  game/save/load_wasm.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/save_wasm.go
  game/sys/achievements.go
  game/sys/haul.go
  game/terr/terrain.go
Labels: feature

#191 Use scroll panels for main menu lists
  game/menu/ui.go
  game/save/load_wasm.go
Labels: usability, ui

#193 Fix layout for small screens
  CHANGELOG.md
  game/res/ui.go
  game/sys/pan_and_zoom.go
Labels: usability, ui

#195 Lock maps behind achievements
  data/json/achievements.json
  data/maps/Desert Valley.asc
  data/maps/River.asc
  data/maps/Swamp Forest.asc
  game/maps/map.go
  game/menu/ui.go
  game/res/achievements/achievements.go
  game/save/load.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/save_wasm.go
  game/sys/achievements.go
  game/sys/init_terrain_map.go
Labels: feature, game rules

#196 Use icons for achievements
  data/json/achievements.json
  game/menu/ui.go
  game/res/achievements/achievements.go
  game/terr/terrain.go
Labels: graphics, ui

#197 Use highlight text color for main menu info/error label
  game/menu/ui.go
Labels: ui

#199 Update GH Pages social preview
  docs/html/index.html
Labels: documentation

#200 Fix: Close unfinished query iteration in achievement check
  game/res/achievements/achievements.go
Labels: bug

#203 Sort scenarios and achievements be unlocked/locked
  CHANGELOG.md
  game/menu/ui.go
Labels: ui

#204 Fix scrolling in WASM build
  game/menu/ui.go
Labels: bug, ui

#213 Add a status bar for various kinds of information
  CHANGELOG.md
  game/comp/components.go
  game/render/terrain.go
  game/render/ui.go
  game/res/ui.go
  game/sys/build.go
  game/sys/save_game.go
  game/sys/update_population.go
  game/sys/update_production.go
  game/sys/update_ui.go
Labels: usability, ui

#214 Improve status bar infos
  CHANGELOG.md
  game/sys/build.go
Labels: usability, ui

#215 Use square brackets for speed control
  CHANGELOG.md
  README.md
  game/res/ui.go
  game/run.go
  game/sys/game_controls.go
  game/sys/pan_and_zoom.go
Labels: usability

#217 Add a cheat / debug shortkey to unlock all scenarios
  game/menu/ui.go
  game/menu/update_ui.go
Labels: ui

#219 Fix: Use random sprites also for buyable land use
  game/res/factory.go
  game/res/selection.go
  game/res/ui.go
  game/sys/build.go
  game/sys/init_terrain.go
  game/sys/init_terrain_map.go
Labels: graphics

#220 Allow for multiple `terrain_below` entries
  data/json/terrain.json
  game/menu/ui.go
  game/render/card_animation.go
  game/render/terrain.go
  game/res/ui.go
  game/terr/terrain.go
Labels: feature, graphics

#222 Add info for no production due to consumption needs
  game/render/terrain.go
Labels: usability, ui

#223 Editor mode
  CHANGELOG.md
  cmd/stats/main.go
  data/maps/Coastline.asc
  data/maps/Desert Valley.asc
  data/maps/River.asc
  data/maps/Rolling Hills.asc
  data/maps/Swamp Forest.asc
  game/menu/ui.go
  game/res/editor.go
  game/res/random_terrains.go
  game/res/ui.go
  game/run.go
  game/save/load.go
  game/save/save.go
  game/sys/achievements.go
  game/sys/build.go
  game/sys/cheats.go
  game/sys/do_consumption.go
  game/sys/do_production.go
  game/sys/init_ui.go
  game/sys/save_game.go
  game/sys/update_stats.go
  game/terr/terrain.go
Labels: feature

#224 Document maps/scenarios
  docs/SCENARIOS.md
  docs/TILESETS.md
  docs/TUTORIAL.md
Labels: documentation

#225 Print symbols in map stats tool
  CHANGELOG.md
  cmd/stats/main.go
  docs/SCENARIOS.md
Labels: infrastructure, maps

#226 Add "Great Plains" scenario
  data/maps/Great Plains.asc
Labels: maps

#227 Fix: add shepherd to windmill `malus_terrain`
  data/json/terrain.json
Labels: bug, game rules

#228 Mark local maps in main menu
  game/menu/ui.go
Labels: ui, maps

#230 Cost balancing
  data/json/terrain.json
Labels: game rules

#232 Fix: save game menu button not working
  game/sys/save_game.go
Labels: bug, ui

#233 Watermill consumes wood, like windmill
  data/json/terrain.json
Labels: game rules, balancing

#231 Terrain unlocking through churches and monasteries
  artwork/sprites/paper/full_48x48/church/church.png
  artwork/sprites/paper/full_48x48/church/church.xcf
  artwork/sprites/paper/full_48x48/monastery/monastery.png
  artwork/sprites/paper/full_48x48/monastery/monastery.xcf
  data/gfx/paper/full_48x48.json
  data/gfx/paper/full_48x48.png
  data/json/rules.json
  data/json/terrain.json
  data/maps/Coastline.asc
  data/maps/Desert Valley.asc
  data/maps/Great Plains.asc
  data/maps/River.asc
  data/maps/Rolling Hills.asc
  data/maps/Swamp Forest.asc
  docs/SCENARIOS.md
  game/comp/components.go
  game/maps/map.go
  game/res/factory.go
  game/res/random_terrains.go
  game/res/rules.go
  game/res/ui.go
  game/run.go
  game/save/load.go
  game/save/save.go
  game/sys/build.go
  game/sys/do_consumption.go
  game/sys/init_terrain_map.go
  game/sys/update_stats.go
  game/terr/terrain.go
Labels: feature, game rules

#235 Balance map random terrains
  data/maps/Coastline.asc
  data/maps/Desert Valley.asc
  data/maps/Great Plains.asc
  data/maps/River.asc
  data/maps/Rolling Hills.asc
  data/maps/Swamp Forest.asc
Labels: maps, balancing

#237 Update changelog
  CHANGELOG.md
Labels: documentation

#238 Balance maps
  data/maps/Great Plains.asc
Labels: maps, balancing

#239 Shorten monastery tooltip for small screens
  data/json/terrain.json
Labels: ui

#242 Show completed achievement in status bar
  game/res/ui.go
  game/sys/achievements.go
Labels: usability, ui

#243 Main menu flipbook
  CHANGELOG.md
  game/menu/ui.go
Labels: usability, ui

#245 Continue button in main menu, sort saved games
  game/menu/ui.go
  game/res/save_time.go
  game/run.go
  game/save/load.go
  game/save/load_nowasm.go
  game/save/load_wasm.go
  game/sys/save_game.go
Labels: usability, ui

#246 Update changelog for savegame sorting
  CHANGELOG.md
Labels: documentation

#247 Amend tooltips for where things can be built
  data/json/terrain.json
Labels: usability, ui

#248 Religious achievements
  data/json/achievements.json
Labels: feature, game rules

#250 Adds scenario "River Delta"
  CHANGELOG.md
  data/maps/River Delta.asc
Labels: maps

#251 Scenario descriptions in tooltips
  CHANGELOG.md
  data/maps/Coastline.asc
  data/maps/Desert Valley.asc
  data/maps/Great Plains.asc
  data/maps/River Delta.asc
  data/maps/River.asc
  data/maps/Rolling Hills.asc
  data/maps/Swamp Forest.asc
  docs/SCENARIOS.md
  game/maps/map.go
  game/menu/ui.go
  game/save/load.go
  game/save/save.go
Labels: documentation, usability, ui

#254 Update build button state 3 times per second
  game/sys/update_stats.go
Labels: ui

#255 Fix consumption of own resources
  game/sys/do_consumption.go
Labels: bug

#257 Use JSON format for maps
  cmd/stats/main.go
  data/maps/Coastline.asc
  data/maps/Coastline.json
  data/maps/Desert Valley.asc
  data/maps/Desert Valley.json
  data/maps/Great Plains.asc
  data/maps/Great Plains.json
  data/maps/River Delta.asc
  data/maps/River Delta.json
  data/maps/River.asc
  data/maps/River.json
  data/maps/Rolling Hills.asc
  data/maps/Rolling Hills.json
  data/maps/Swamp Forest.asc
  data/maps/Swamp Forest.json
  docs/SCENARIOS.md
  game/save/load.go
  game/save/load_nowasm.go
  game/save/load_wasm.go
  game/save/save.go
  game/save/save_nowasm.go
  game/save/types.go
Labels: maps

#258 Tweak map symbols to be more consistent
  data/json/terrain.json
  data/maps/Coastline.json
  data/maps/Desert Valley.json
  data/maps/Great Plains.json
  data/maps/River Delta.json
  data/maps/River.json
  data/maps/Rolling Hills.json
  data/maps/Swamp Forest.json
Labels: internal, maps

#259 Catch and fix map random terrain problems
  data/maps/Coastline.json
  data/maps/Desert Valley.json
  data/maps/Great Plains.json
  data/maps/River Delta.json
  data/maps/River.json
  data/maps/Rolling Hills.json
  data/maps/Swamp Forest.json
  game/save/load.go
Labels: bug

#181 Build macOS app and extend the README.md regarding macOS release
  .github/tiny-world.app/Contents/Info.plist
  .github/tiny-world.app/Contents/Resources/tiny-world.icns
  .github/workflows/release.yml
  .github/workflows/test-release.yml
  .gitignore
  INSTALL.md
  README.md
Labels: infrastructure

#260 More achievements: bridges and mills
  data/json/achievements.json
  data/maps/Coastline.json
  data/maps/River Delta.json
  game/menu/ui.go
  game/res/achievements/achievements.go
  game/res/sprites.go
Labels: game rules, maps

#261 Change WASM savegame key to `mlange-42/tiny-world/save/`
  game/save/save_wasm.go
Labels: internal

#262 Fix: In editor, add special marker only to terrains
  game/res/ui.go
Labels: bug, ui
